# site variables ----
title: ?nteetor
email: nathanteetor@gmail.com
description: >-
  The blog of the one and only Nathan Teetor.
baseurl: ""
url: ""

# build settings ----
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# exclude ----
exclude:
  - README.md

# notes ----
#
# Fonts
#   - for drop cap use https://fonts.google.com/specimen/Cormorant+Unicase
#   - 
#